# No Fedora, antes de rodar o docker:
# sudo setenforce 0
# docker-compose up -d

version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:80" # Render usa porta 10000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=meu_db
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=meu_db
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
